### ISSUE TITLE
Delegate to Ember.OrderedSet if possible

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-ordered-set#11]
We should try to keep the payload small for users of this package by not including our own version of `OrderedSet` if it is available in `ember-source` already.

We should use https://github.com/ember-cli/ember-cli-version-checker/ to check what Ember version is used and if it is a version where we know for sure that it has `Ember.OrderedSet` we can delegate to that instead of bundling our own code.

**Comment by rwjblue** [comment]
Yep, totally agreed!
