### ISSUE TITLE
Delegate to native `Set` class if possible

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-ordered-set#14]
According to https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Set the native `Set` class also preserves the insertion order so we should probably delegate to that one if the browser targets allow it.

Are there any differences between `OrderedSet` and native `Set` that I'm missing?

/cc @rwjblue

**Comment by Turbo87** [comment]
The main differences seem to be:

- The constructor does not take any arguments
- A static `create()` method exists for symmetry with `Ember.Object`
- A static `length` property does not exist on `OrderedSet`
- `OrderedSet` has an `isEmpty()` method
- There are no `entries()`, `keys()` and `values()` methods, but there is a
  `toArray()` method instead
- The `@@iterator` symbol is not defined
- `OrderedSet` has a `copy()` method

**Comment by Turbo87** [comment]
Given all these API differences it does not seem viable to use `OrderedSet` as a polyfill for the native `Set` class. It might make more sense to provide a dedicated `ember-set-polyfill` addon that polyfills the native API instead of `Ember.OrderedSet`.

**Comment by rwjblue** [comment]
> It might make more sense to provide a dedicated ember-set-polyfill addon that polyfills the native API instead of Ember.OrderedSet.

I think folks would be better serviced by core-js's `Set` (via ember-cli-babel's `includePolyfill` option) instead...
