### ISSUE TITLE
@ember/ordered-set does not avoid deprecation warnings

### ISSUE THREAD

**Issue by ef4** [emberjs/ember-ordered-set#19]
My understanding of this addon is that people should switch to it to avoid deprecation warnings from the built-in ordered-set inside Ember. Which is what ember-data is doing [here](https://github.com/emberjs/data/commit/d478a04ee3e570b5ea9eacf5d16fe78db02cd873).

But using ember-data 3.1.1 (which is importing from `@ember/ordered-set`) with ember-canary we still get the deprecation. Presumably because @ember/ordered-set falls back to the built-in implementation in an effort not to bloat code size.

Do you want PRs to ember and ordered-set to create a deprecation-free private path?

cc @savvymas

**Comment by rwjblue** [comment]
> My understanding of this addon is that people should switch to it to avoid deprecation warnings from the built-in ordered-set inside Ember.

👍 

> But using ember-data 3.1.1 (which is importing from @ember/ordered-set) with ember-canary we still get the deprecation. Presumably because falls back to the built-in implementation in an effort not to bloat code size.

Yes, that was exactly the goal. 🤔 

> Do you want PRs to ember and ordered-set to create a deprecation-free private path?

Yes, please 🙏 .

**Comment by rwjblue** [comment]
I think the most straightforward way to do this is:

* add via a private env flag (similar to [this](https://github.com/emberjs/ember.js/blob/ff6bc16b72d3684eae644185c24b538119875bb6/packages/ember-environment/lib/env.ts#L137))
* Update the deprecation conditions [here](https://github.com/emberjs/ember.js/blob/ff6bc16b72d3684eae644185c24b538119875bb6/packages/%40ember/map/lib/ordered-set.js#L17) to check that private env flag (and suppress the deprecation when it is `true`)
* Add the flag to this addons config/environment.js (similar to [this](https://github.com/emberjs/ember-2-legacy/blob/fe7c324a20ab59662840c50112d9d40c83db426d/config/environment.js#L27))

**Comment by ef4** [comment]
I think we don't want a global flag though -- anybody who is trying to use Ember.OrderedSet directly should still see a deprecation until they switch to using it via `@ember/ordered-set`.

**Comment by rwjblue** [comment]
@ef4 - Ahh, good point. In that case, I think we need to add the following to my steps above:

* Update [the main module](https://github.com/emberjs/ember.js/blob/master/packages/@ember/map/lib/ordered-set.js) to have two exports, a non-deprecated (but private) base class and an extended class that adds the deprecation that exists today
* Update [the main exports module](https://github.com/emberjs/ember.js/blob/ff6bc16b72d3684eae644185c24b538119875bb6/packages/ember/index.js#L185) to ensure that `Ember.OrderedSet` is using the deprecated class, and also add an `Ember.__OrderedSet__` 
* Update [this addons index.js](https://github.com/emberjs/ember-ordered-set/blob/43ed8b5ce7b16e753503386ed9228b24b9d5cec3/addon/index.js#L157) to be `OrderedSet = Ember.__OrderedSet__ || Ember.OrderedSet;`

What do you think?

**Comment by ef4** [comment]
Yup, @savvymas is already embarking in that direction.
