### ISSUE TITLE
Licensing Terms Unclear

### ISSUE THREAD

**Issue by ska2342** [emberjs/ember-ordered-set#44]
Dear developers,

neither the copyright line in the LICENSE file, nor the authors field in package.json nor any headers of source code files list the copyright holders. This prevents commercial adoption of this project.

Do you plan to clarify that, ideally in a way that allows appropriate tooling to pick up the information automatically? It could be as easy as adding the copyright holders to line 3 in the LICENSE file.

Thanks,
Stefan

**Comment by locks** [comment]
Thanks for bringing this up. I have opened a PR to address this!
